### ISSUE TITLE
Depends on connection, which is archived now

### ISSUE THREAD

**Issue by pmiddend** [alasconnect/ldap-client#10]
See [the repo](https://github.com/vincenthz/hs-connection). connection also depends on an old version of tls, which breaks this whole package in nixpkgs.

**Comment by boj** [comment]
@pmiddend We're not directly maintaining this repo right now. Patches are welcome, though!

**Comment by pmiddend** [comment]
Ah, too bad! But I created #11  to fix the dependency.
